version: '3.6'

services:

  state-machine-analyze-builder:
    build:
      context: ../
      dockerfile: Dockerfile
    image: state-machine-analyze-builder
    container_name: state-machine-analyze-builder
    volumes:
      - ../../:/project/state-machine/
    command: go fmt ...
